/* =============================================================================
   SquadTrip - city suggestions with real timezones.
   Typing a destination or stop fills the timezone automatically, so the
   clocks are right even when you create the trip from somewhere else.
   Anything not on this list is still accepted verbatim.
   ========================================================================== */
window.CITIES = [
  // ---- United States ----
  { c: "New York, USA", tz: "America/New_York" },
  { c: "Washington DC, USA", tz: "America/New_York" },
  { c: "Boston, USA", tz: "America/New_York" },
  { c: "Philadelphia, USA", tz: "America/New_York" },
  { c: "Miami, USA", tz: "America/New_York" },
  { c: "Orlando, USA", tz: "America/New_York" },
  { c: "Key West, USA", tz: "America/New_York" },
  { c: "Atlanta, USA", tz: "America/New_York" },
  { c: "Charleston, USA", tz: "America/New_York" },
  { c: "Savannah, USA", tz: "America/New_York" },
  { c: "Nashville, USA", tz: "America/Chicago" },
  { c: "New Orleans, USA", tz: "America/Chicago" },
  { c: "Chicago, USA", tz: "America/Chicago" },
  { c: "Austin, USA", tz: "America/Chicago" },
  { c: "Dallas, USA", tz: "America/Chicago" },
  { c: "Houston, USA", tz: "America/Chicago" },
  { c: "Minneapolis, USA", tz: "America/Chicago" },
  { c: "Denver, USA", tz: "America/Denver" },
  { c: "Aspen, USA", tz: "America/Denver" },
  { c: "Park City, USA", tz: "America/Denver" },
  { c: "Jackson Hole, USA", tz: "America/Denver" },
  { c: "Santa Fe, USA", tz: "America/Denver" },
  { c: "Phoenix, USA", tz: "America/Phoenix" },
  { c: "Scottsdale, USA", tz: "America/Phoenix" },
  { c: "Sedona, USA", tz: "America/Phoenix" },
  { c: "Las Vegas, USA", tz: "America/Los_Angeles" },
  { c: "Los Angeles, USA", tz: "America/Los_Angeles" },
  { c: "San Diego, USA", tz: "America/Los_Angeles" },
  { c: "San Francisco, USA", tz: "America/Los_Angeles" },
  { c: "Napa Valley, USA", tz: "America/Los_Angeles" },
  { c: "Palm Springs, USA", tz: "America/Los_Angeles" },
  { c: "Seattle, USA", tz: "America/Los_Angeles" },
  { c: "Portland, USA", tz: "America/Los_Angeles" },
  { c: "Honolulu, USA", tz: "Pacific/Honolulu" },
  { c: "Maui, USA", tz: "Pacific/Honolulu" },
  { c: "Kauai, USA", tz: "Pacific/Honolulu" },
  { c: "Anchorage, USA", tz: "America/Anchorage" },
  // ---- Canada ----
  { c: "Toronto, Canada", tz: "America/Toronto" },
  { c: "Montreal, Canada", tz: "America/Toronto" },
  { c: "Quebec City, Canada", tz: "America/Toronto" },
  { c: "Vancouver, Canada", tz: "America/Vancouver" },
  { c: "Whistler, Canada", tz: "America/Vancouver" },
  { c: "Banff, Canada", tz: "America/Edmonton" },
  // ---- Mexico, Caribbean, Central America ----
  { c: "Cancun, Mexico", tz: "America/Cancun" },
  { c: "Tulum, Mexico", tz: "America/Cancun" },
  { c: "Playa del Carmen, Mexico", tz: "America/Cancun" },
  { c: "Cozumel, Mexico", tz: "America/Cancun" },
  { c: "Mexico City, Mexico", tz: "America/Mexico_City" },
  { c: "Oaxaca, Mexico", tz: "America/Mexico_City" },
  { c: "Puerto Vallarta, Mexico", tz: "America/Mexico_City" },
  { c: "Sayulita, Mexico", tz: "America/Mazatlan" },
  { c: "Cabo San Lucas, Mexico", tz: "America/Mazatlan" },
  { c: "Punta Cana, Dominican Republic", tz: "America/Santo_Domingo" },
  { c: "Montego Bay, Jamaica", tz: "America/Jamaica" },
  { c: "Negril, Jamaica", tz: "America/Jamaica" },
  { c: "Nassau, Bahamas", tz: "America/Nassau" },
  { c: "Turks and Caicos", tz: "America/Grand_Turk" },
  { c: "Aruba", tz: "America/Aruba" },
  { c: "Barbados", tz: "America/Barbados" },
  { c: "St. Lucia", tz: "America/St_Lucia" },
  { c: "Antigua", tz: "America/Antigua" },
  { c: "San Juan, Puerto Rico", tz: "America/Puerto_Rico" },
  { c: "Tamarindo, Costa Rica", tz: "America/Costa_Rica" },
  { c: "La Fortuna, Costa Rica", tz: "America/Costa_Rica" },
  { c: "Belize City, Belize", tz: "America/Belize" },
  { c: "Panama City, Panama", tz: "America/Panama" },
  // ---- South America ----
  { c: "Rio de Janeiro, Brazil", tz: "America/Sao_Paulo" },
  { c: "Sao Paulo, Brazil", tz: "America/Sao_Paulo" },
  { c: "Buenos Aires, Argentina", tz: "America/Argentina/Buenos_Aires" },
  { c: "Mendoza, Argentina", tz: "America/Argentina/Mendoza" },
  { c: "Patagonia, Argentina", tz: "America/Argentina/Buenos_Aires" },
  { c: "Santiago, Chile", tz: "America/Santiago" },
  { c: "Lima, Peru", tz: "America/Lima" },
  { c: "Cusco, Peru", tz: "America/Lima" },
  { c: "Cartagena, Colombia", tz: "America/Bogota" },
  { c: "Medellin, Colombia", tz: "America/Bogota" },
  { c: "Bogota, Colombia", tz: "America/Bogota" },
  { c: "Quito, Ecuador", tz: "America/Guayaquil" },
  { c: "Montevideo, Uruguay", tz: "America/Montevideo" },
  // ---- UK & Ireland ----
  { c: "London, UK", tz: "Europe/London" },
  { c: "Edinburgh, Scotland", tz: "Europe/London" },
  { c: "Dublin, Ireland", tz: "Europe/Dublin" },
  // ---- Western & Northern Europe ----
  { c: "Paris, France", tz: "Europe/Paris" },
  { c: "Nice, France", tz: "Europe/Paris" },
  { c: "Cannes, France", tz: "Europe/Paris" },
  { c: "Bordeaux, France", tz: "Europe/Paris" },
  { c: "Provence, France", tz: "Europe/Paris" },
  { c: "Amsterdam, Netherlands", tz: "Europe/Amsterdam" },
  { c: "Brussels, Belgium", tz: "Europe/Brussels" },
  { c: "Berlin, Germany", tz: "Europe/Berlin" },
  { c: "Munich, Germany", tz: "Europe/Berlin" },
  { c: "Vienna, Austria", tz: "Europe/Vienna" },
  { c: "Zurich, Switzerland", tz: "Europe/Zurich" },
  { c: "Interlaken, Switzerland", tz: "Europe/Zurich" },
  { c: "Zermatt, Switzerland", tz: "Europe/Zurich" },
  { c: "Copenhagen, Denmark", tz: "Europe/Copenhagen" },
  { c: "Stockholm, Sweden", tz: "Europe/Stockholm" },
  { c: "Oslo, Norway", tz: "Europe/Oslo" },
  { c: "Helsinki, Finland", tz: "Europe/Helsinki" },
  { c: "Reykjavik, Iceland", tz: "Atlantic/Reykjavik" },
  // ---- Southern Europe ----
  { c: "Barcelona, Spain", tz: "Europe/Madrid" },
  { c: "Madrid, Spain", tz: "Europe/Madrid" },
  { c: "Seville, Spain", tz: "Europe/Madrid" },
  { c: "Valencia, Spain", tz: "Europe/Madrid" },
  { c: "San Sebastian, Spain", tz: "Europe/Madrid" },
  { c: "Ibiza, Spain", tz: "Europe/Madrid" },
  { c: "Mallorca, Spain", tz: "Europe/Madrid" },
  { c: "Lisbon, Portugal", tz: "Europe/Lisbon" },
  { c: "Porto, Portugal", tz: "Europe/Lisbon" },
  { c: "Algarve, Portugal", tz: "Europe/Lisbon" },
  { c: "Madeira, Portugal", tz: "Atlantic/Madeira" },
  { c: "Rome, Italy", tz: "Europe/Rome" },
  { c: "Florence, Italy", tz: "Europe/Rome" },
  { c: "Venice, Italy", tz: "Europe/Rome" },
  { c: "Milan, Italy", tz: "Europe/Rome" },
  { c: "Naples, Italy", tz: "Europe/Rome" },
  { c: "Amalfi Coast, Italy", tz: "Europe/Rome" },
  { c: "Positano, Italy", tz: "Europe/Rome" },
  { c: "Capri, Italy", tz: "Europe/Rome" },
  { c: "Sicily, Italy", tz: "Europe/Rome" },
  { c: "Tuscany, Italy", tz: "Europe/Rome" },
  { c: "Lake Como, Italy", tz: "Europe/Rome" },
  { c: "Athens, Greece", tz: "Europe/Athens" },
  { c: "Santorini, Greece", tz: "Europe/Athens" },
  { c: "Mykonos, Greece", tz: "Europe/Athens" },
  { c: "Crete, Greece", tz: "Europe/Athens" },
  { c: "Corfu, Greece", tz: "Europe/Athens" },
  { c: "Dubrovnik, Croatia", tz: "Europe/Zagreb" },
  { c: "Split, Croatia", tz: "Europe/Zagreb" },
  { c: "Hvar, Croatia", tz: "Europe/Zagreb" },
  { c: "Budapest, Hungary", tz: "Europe/Budapest" },
  { c: "Prague, Czech Republic", tz: "Europe/Prague" },
  { c: "Krakow, Poland", tz: "Europe/Warsaw" },
  { c: "Ljubljana, Slovenia", tz: "Europe/Ljubljana" },
  { c: "Malta", tz: "Europe/Malta" },
  { c: "Istanbul, Turkey", tz: "Europe/Istanbul" },
  { c: "Cappadocia, Turkey", tz: "Europe/Istanbul" },
  { c: "Bodrum, Turkey", tz: "Europe/Istanbul" },
  // ---- Africa & Middle East ----
  { c: "Marrakech, Morocco", tz: "Africa/Casablanca" },
  { c: "Fes, Morocco", tz: "Africa/Casablanca" },
  { c: "Casablanca, Morocco", tz: "Africa/Casablanca" },
  { c: "Cairo, Egypt", tz: "Africa/Cairo" },
  { c: "Cape Town, South Africa", tz: "Africa/Johannesburg" },
  { c: "Johannesburg, South Africa", tz: "Africa/Johannesburg" },
  { c: "Kruger, South Africa", tz: "Africa/Johannesburg" },
  { c: "Nairobi, Kenya", tz: "Africa/Nairobi" },
  { c: "Zanzibar, Tanzania", tz: "Africa/Dar_es_Salaam" },
  { c: "Serengeti, Tanzania", tz: "Africa/Dar_es_Salaam" },
  { c: "Accra, Ghana", tz: "Africa/Accra" },
  { c: "Lagos, Nigeria", tz: "Africa/Lagos" },
  { c: "Dakar, Senegal", tz: "Africa/Dakar" },
  { c: "Seychelles", tz: "Indian/Mahe" },
  { c: "Mauritius", tz: "Indian/Mauritius" },
  { c: "Dubai, UAE", tz: "Asia/Dubai" },
  { c: "Abu Dhabi, UAE", tz: "Asia/Dubai" },
  { c: "Doha, Qatar", tz: "Asia/Qatar" },
  { c: "Tel Aviv, Israel", tz: "Asia/Jerusalem" },
  { c: "Amman, Jordan", tz: "Asia/Amman" },
  // ---- Asia ----
  { c: "Tokyo, Japan", tz: "Asia/Tokyo" },
  { c: "Kyoto, Japan", tz: "Asia/Tokyo" },
  { c: "Osaka, Japan", tz: "Asia/Tokyo" },
  { c: "Hakone, Japan", tz: "Asia/Tokyo" },
  { c: "Seoul, South Korea", tz: "Asia/Seoul" },
  { c: "Bangkok, Thailand", tz: "Asia/Bangkok" },
  { c: "Phuket, Thailand", tz: "Asia/Bangkok" },
  { c: "Chiang Mai, Thailand", tz: "Asia/Bangkok" },
  { c: "Koh Samui, Thailand", tz: "Asia/Bangkok" },
  { c: "Bali, Indonesia", tz: "Asia/Makassar" },
  { c: "Jakarta, Indonesia", tz: "Asia/Jakarta" },
  { c: "Singapore", tz: "Asia/Singapore" },
  { c: "Kuala Lumpur, Malaysia", tz: "Asia/Kuala_Lumpur" },
  { c: "Ho Chi Minh City, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Hanoi, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Hoi An, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Siem Reap, Cambodia", tz: "Asia/Phnom_Penh" },
  { c: "Manila, Philippines", tz: "Asia/Manila" },
  { c: "Palawan, Philippines", tz: "Asia/Manila" },
  { c: "Hong Kong", tz: "Asia/Hong_Kong" },
  { c: "Taipei, Taiwan", tz: "Asia/Taipei" },
  { c: "Shanghai, China", tz: "Asia/Shanghai" },
  { c: "Beijing, China", tz: "Asia/Shanghai" },
  { c: "Delhi, India", tz: "Asia/Kolkata" },
  { c: "Mumbai, India", tz: "Asia/Kolkata" },
  { c: "Jaipur, India", tz: "Asia/Kolkata" },
  { c: "Udaipur, India", tz: "Asia/Kolkata" },
  { c: "Goa, India", tz: "Asia/Kolkata" },
  { c: "Kerala, India", tz: "Asia/Kolkata" },
  { c: "Colombo, Sri Lanka", tz: "Asia/Colombo" },
  { c: "Kathmandu, Nepal", tz: "Asia/Kathmandu" },
  { c: "Maldives", tz: "Indian/Maldives" },
  // ---- Oceania ----
  { c: "Sydney, Australia", tz: "Australia/Sydney" },
  { c: "Melbourne, Australia", tz: "Australia/Melbourne" },
  { c: "Gold Coast, Australia", tz: "Australia/Brisbane" },
  { c: "Cairns, Australia", tz: "Australia/Brisbane" },
  { c: "Perth, Australia", tz: "Australia/Perth" },
  { c: "Auckland, New Zealand", tz: "Pacific/Auckland" },
  { c: "Queenstown, New Zealand", tz: "Pacific/Auckland" },
  { c: "Fiji", tz: "Pacific/Fiji" },
  { c: "Bora Bora", tz: "Pacific/Tahiti" },
  { c: "Tahiti", tz: "Pacific/Tahiti" },
  { c: "Cook Islands", tz: "Pacific/Rarotonga" },
  // ---- United States, fuller coverage ----
  // Eastern
  { c: "Tampa, USA", tz: "America/New_York" },
  { c: "St. Petersburg, USA", tz: "America/New_York" },
  { c: "Clearwater, USA", tz: "America/New_York" },
  { c: "Sarasota, USA", tz: "America/New_York" },
  { c: "Naples, USA", tz: "America/New_York" },
  { c: "Fort Myers, USA", tz: "America/New_York" },
  { c: "Fort Lauderdale, USA", tz: "America/New_York" },
  { c: "West Palm Beach, USA", tz: "America/New_York" },
  { c: "Jacksonville, USA", tz: "America/New_York" },
  { c: "St. Augustine, USA", tz: "America/New_York" },
  { c: "Daytona Beach, USA", tz: "America/New_York" },
  { c: "Amelia Island, USA", tz: "America/New_York" },
  { c: "Myrtle Beach, USA", tz: "America/New_York" },
  { c: "Hilton Head, USA", tz: "America/New_York" },
  { c: "Outer Banks, USA", tz: "America/New_York" },
  // The Outer Banks is not one place, it is a string of towns, and you rent a
  // house in one of them. Same for the rest of the Carolina and Gulf coasts.
  { c: "Corolla, USA", tz: "America/New_York" },
  { c: "Duck, USA", tz: "America/New_York" },
  { c: "Southern Shores, USA", tz: "America/New_York" },
  { c: "Kitty Hawk, USA", tz: "America/New_York" },
  { c: "Kill Devil Hills, USA", tz: "America/New_York" },
  { c: "Nags Head, USA", tz: "America/New_York" },
  { c: "Manteo, USA", tz: "America/New_York" },
  { c: "Rodanthe, USA", tz: "America/New_York" },
  { c: "Salvo, USA", tz: "America/New_York" },
  { c: "Avon, USA", tz: "America/New_York" },
  { c: "Buxton, USA", tz: "America/New_York" },
  { c: "Hatteras, USA", tz: "America/New_York" },
  { c: "Ocracoke, USA", tz: "America/New_York" },
  { c: "Emerald Isle, USA", tz: "America/New_York" },
  { c: "Atlantic Beach, USA", tz: "America/New_York" },
  { c: "Beaufort, North Carolina, USA", tz: "America/New_York" },
  { c: "Topsail Island, USA", tz: "America/New_York" },
  { c: "Wrightsville Beach, USA", tz: "America/New_York" },
  { c: "Carolina Beach, USA", tz: "America/New_York" },
  { c: "Kure Beach, USA", tz: "America/New_York" },
  { c: "Bald Head Island, USA", tz: "America/New_York" },
  { c: "Oak Island, USA", tz: "America/New_York" },
  { c: "Ocean Isle Beach, USA", tz: "America/New_York" },
  { c: "Sunset Beach, USA", tz: "America/New_York" },
  { c: "Wilmington, USA", tz: "America/New_York" },
  { c: "North Myrtle Beach, USA", tz: "America/New_York" },
  { c: "Pawleys Island, USA", tz: "America/New_York" },
  { c: "Isle of Palms, USA", tz: "America/New_York" },
  { c: "Sullivan\'s Island, USA", tz: "America/New_York" },
  { c: "Folly Beach, USA", tz: "America/New_York" },
  { c: "Kiawah Island, USA", tz: "America/New_York" },
  { c: "Edisto Beach, USA", tz: "America/New_York" },
  { c: "Tybee Island, USA", tz: "America/New_York" },
  { c: "St. Simons Island, USA", tz: "America/New_York" },
  { c: "Sea Island, USA", tz: "America/New_York" },
  { c: "Jekyll Island, USA", tz: "America/New_York" },
  { c: "Fernandina Beach, USA", tz: "America/New_York" },
  { c: "Ponte Vedra Beach, USA", tz: "America/New_York" },
  { c: "New Smyrna Beach, USA", tz: "America/New_York" },
  { c: "Cocoa Beach, USA", tz: "America/New_York" },
  { c: "Vero Beach, USA", tz: "America/New_York" },
  { c: "Jupiter, USA", tz: "America/New_York" },
  { c: "Delray Beach, USA", tz: "America/New_York" },
  { c: "Boca Raton, USA", tz: "America/New_York" },
  { c: "Anna Maria Island, USA", tz: "America/New_York" },
  { c: "Siesta Key, USA", tz: "America/New_York" },
  { c: "Sanibel Island, USA", tz: "America/New_York" },
  { c: "Captiva Island, USA", tz: "America/New_York" },
  { c: "Marco Island, USA", tz: "America/New_York" },
  { c: "Clearwater Beach, USA", tz: "America/New_York" },
  { c: "St. Pete Beach, USA", tz: "America/New_York" },
  { c: "Islamorada, USA", tz: "America/New_York" },
  { c: "Marathon, Florida, USA", tz: "America/New_York" },
  { c: "Asheville, USA", tz: "America/New_York" },
  { c: "Charlotte, USA", tz: "America/New_York" },
  { c: "Raleigh, USA", tz: "America/New_York" },
  { c: "Greenville, USA", tz: "America/New_York" },
  { c: "Richmond, USA", tz: "America/New_York" },
  { c: "Virginia Beach, USA", tz: "America/New_York" },
  { c: "Baltimore, USA", tz: "America/New_York" },
  { c: "Annapolis, USA", tz: "America/New_York" },
  { c: "Rehoboth Beach, USA", tz: "America/New_York" },
  { c: "Dewey Beach, USA", tz: "America/New_York" },
  { c: "Bethany Beach, USA", tz: "America/New_York" },
  { c: "Fenwick Island, USA", tz: "America/New_York" },
  { c: "Ocean City, Maryland, USA", tz: "America/New_York" },
  { c: "Chincoteague, USA", tz: "America/New_York" },
  { c: "St. Michaels, USA", tz: "America/New_York" },
  { c: "Long Beach Island, USA", tz: "America/New_York" },
  { c: "Avalon, New Jersey, USA", tz: "America/New_York" },
  { c: "Stone Harbor, USA", tz: "America/New_York" },
  { c: "Wildwood, USA", tz: "America/New_York" },
  { c: "Ocean City, New Jersey, USA", tz: "America/New_York" },
  { c: "Asbury Park, USA", tz: "America/New_York" },
  { c: "Point Pleasant Beach, USA", tz: "America/New_York" },
  { c: "Atlantic City, USA", tz: "America/New_York" },
  { c: "Cape May, USA", tz: "America/New_York" },
  { c: "Pittsburgh, USA", tz: "America/New_York" },
  { c: "Cleveland, USA", tz: "America/New_York" },
  { c: "Columbus, USA", tz: "America/New_York" },
  { c: "Cincinnati, USA", tz: "America/New_York" },
  { c: "Detroit, USA", tz: "America/Detroit" },
  { c: "Traverse City, USA", tz: "America/Detroit" },
  { c: "Saugatuck, USA", tz: "America/Detroit" },
  { c: "South Haven, USA", tz: "America/Detroit" },
  { c: "Holland, Michigan, USA", tz: "America/Detroit" },
  { c: "Grand Haven, USA", tz: "America/Detroit" },
  { c: "Petoskey, USA", tz: "America/Detroit" },
  { c: "Mackinac Island, USA", tz: "America/Detroit" },
  { c: "Indianapolis, USA", tz: "America/Indiana/Indianapolis" },
  { c: "Louisville, USA", tz: "America/Kentucky/Louisville" },
  { c: "Knoxville, USA", tz: "America/New_York" },
  { c: "Gatlinburg, USA", tz: "America/New_York" },
  { c: "Buffalo, USA", tz: "America/New_York" },
  { c: "Niagara Falls, USA", tz: "America/New_York" },
  { c: "Lake Placid, USA", tz: "America/New_York" },
  { c: "Hudson Valley, USA", tz: "America/New_York" },
  { c: "Finger Lakes, USA", tz: "America/New_York" },
  { c: "The Hamptons, USA", tz: "America/New_York" },
  { c: "Montauk, USA", tz: "America/New_York" },
  { c: "Fire Island, USA", tz: "America/New_York" },
  { c: "Block Island, USA", tz: "America/New_York" },
  { c: "Narragansett, USA", tz: "America/New_York" },
  { c: "Watch Hill, USA", tz: "America/New_York" },
  { c: "Mystic, USA", tz: "America/New_York" },
  { c: "Provincetown, USA", tz: "America/New_York" },
  { c: "Chatham, USA", tz: "America/New_York" },
  { c: "Hyannis, USA", tz: "America/New_York" },
  { c: "Falmouth, USA", tz: "America/New_York" },
  { c: "Wellfleet, USA", tz: "America/New_York" },
  { c: "Ogunquit, USA", tz: "America/New_York" },
  { c: "Kennebunkport, USA", tz: "America/New_York" },
  { c: "Old Orchard Beach, USA", tz: "America/New_York" },
  { c: "Cape Cod, USA", tz: "America/New_York" },
  { c: "Nantucket, USA", tz: "America/New_York" },
  { c: "Martha's Vineyard, USA", tz: "America/New_York" },
  { c: "Newport, USA", tz: "America/New_York" },
  { c: "Portland, Maine, USA", tz: "America/New_York" },
  { c: "Bar Harbor, USA", tz: "America/New_York" },
  { c: "Burlington, USA", tz: "America/New_York" },
  { c: "Stowe, USA", tz: "America/New_York" },
  // Central
  { c: "San Antonio, USA", tz: "America/Chicago" },
  { c: "Fort Worth, USA", tz: "America/Chicago" },
  { c: "Galveston, USA", tz: "America/Chicago" },
  { c: "South Padre Island, USA", tz: "America/Chicago" },
  { c: "Memphis, USA", tz: "America/Chicago" },
  { c: "Birmingham, USA", tz: "America/Chicago" },
  { c: "Gulf Shores, USA", tz: "America/Chicago" },
  { c: "Destin, USA", tz: "America/Chicago" },
  { c: "Panama City Beach, USA", tz: "America/Chicago" },
  { c: "30A, USA", tz: "America/Chicago" },
  { c: "Seaside, Florida, USA", tz: "America/Chicago" },
  { c: "Rosemary Beach, USA", tz: "America/Chicago" },
  { c: "Watercolor, USA", tz: "America/Chicago" },
  { c: "Grayton Beach, USA", tz: "America/Chicago" },
  { c: "Santa Rosa Beach, USA", tz: "America/Chicago" },
  { c: "Pensacola Beach, USA", tz: "America/Chicago" },
  { c: "Navarre Beach, USA", tz: "America/Chicago" },
  { c: "Orange Beach, USA", tz: "America/Chicago" },
  { c: "Dauphin Island, USA", tz: "America/Chicago" },
  { c: "Port Aransas, USA", tz: "America/Chicago" },
  { c: "Rockport, Texas, USA", tz: "America/Chicago" },
  { c: "Corpus Christi, USA", tz: "America/Chicago" },
  { c: "Biloxi, USA", tz: "America/Chicago" },
  { c: "Little Rock, USA", tz: "America/Chicago" },
  { c: "St. Louis, USA", tz: "America/Chicago" },
  { c: "Kansas City, USA", tz: "America/Chicago" },
  { c: "Branson, USA", tz: "America/Chicago" },
  { c: "Des Moines, USA", tz: "America/Chicago" },
  { c: "Omaha, USA", tz: "America/Chicago" },
  { c: "Milwaukee, USA", tz: "America/Chicago" },
  { c: "Lake Geneva, USA", tz: "America/Chicago" },
  { c: "Door County, USA", tz: "America/Chicago" },
  { c: "Oklahoma City, USA", tz: "America/Chicago" },
  { c: "Tulsa, USA", tz: "America/Chicago" },
  // Mountain
  { c: "Salt Lake City, USA", tz: "America/Denver" },
  { c: "Moab, USA", tz: "America/Denver" },
  { c: "Telluride, USA", tz: "America/Denver" },
  { c: "Breckenridge, USA", tz: "America/Denver" },
  { c: "Vail, USA", tz: "America/Denver" },
  { c: "Steamboat Springs, USA", tz: "America/Denver" },
  { c: "Bozeman, USA", tz: "America/Denver" },
  { c: "Big Sky, USA", tz: "America/Denver" },
  { c: "Whitefish, USA", tz: "America/Denver" },
  { c: "Sun Valley, USA", tz: "America/Denver" },
  { c: "Albuquerque, USA", tz: "America/Denver" },
  { c: "Taos, USA", tz: "America/Denver" },
  { c: "Boise, USA", tz: "America/Boise" },
  { c: "Tucson, USA", tz: "America/Phoenix" },
  // Pacific
  { c: "Sacramento, USA", tz: "America/Los_Angeles" },
  { c: "Lake Tahoe, USA", tz: "America/Los_Angeles" },
  { c: "Santa Barbara, USA", tz: "America/Los_Angeles" },
  { c: "Monterey, USA", tz: "America/Los_Angeles" },
  { c: "Carmel, USA", tz: "America/Los_Angeles" },
  { c: "Big Sur, USA", tz: "America/Los_Angeles" },
  { c: "Sonoma, USA", tz: "America/Los_Angeles" },
  { c: "Newport Beach, USA", tz: "America/Los_Angeles" },
  { c: "Malibu, USA", tz: "America/Los_Angeles" },
  { c: "Manhattan Beach, USA", tz: "America/Los_Angeles" },
  { c: "Hermosa Beach, USA", tz: "America/Los_Angeles" },
  { c: "Huntington Beach, USA", tz: "America/Los_Angeles" },
  { c: "Laguna Beach, USA", tz: "America/Los_Angeles" },
  { c: "Dana Point, USA", tz: "America/Los_Angeles" },
  { c: "Coronado, USA", tz: "America/Los_Angeles" },
  { c: "La Jolla, USA", tz: "America/Los_Angeles" },
  { c: "Encinitas, USA", tz: "America/Los_Angeles" },
  { c: "Carlsbad, USA", tz: "America/Los_Angeles" },
  { c: "Ventura, USA", tz: "America/Los_Angeles" },
  { c: "Pismo Beach, USA", tz: "America/Los_Angeles" },
  { c: "Morro Bay, USA", tz: "America/Los_Angeles" },
  { c: "Cambria, USA", tz: "America/Los_Angeles" },
  { c: "Santa Cruz, USA", tz: "America/Los_Angeles" },
  { c: "Half Moon Bay, USA", tz: "America/Los_Angeles" },
  { c: "Bodega Bay, USA", tz: "America/Los_Angeles" },
  { c: "Mendocino, USA", tz: "America/Los_Angeles" },
  { c: "Cannon Beach, USA", tz: "America/Los_Angeles" },
  { c: "Seaside, Oregon, USA", tz: "America/Los_Angeles" },
  { c: "Newport, Oregon, USA", tz: "America/Los_Angeles" },
  { c: "Lincoln City, USA", tz: "America/Los_Angeles" },
  { c: "Ocean Shores, USA", tz: "America/Los_Angeles" },
  { c: "Santa Monica, USA", tz: "America/Los_Angeles" },
  { c: "Spokane, USA", tz: "America/Los_Angeles" },
  { c: "Bend, USA", tz: "America/Los_Angeles" },
  { c: "Reno, USA", tz: "America/Los_Angeles" },
  { c: "Big Island, USA", tz: "Pacific/Honolulu" },
  { c: "Juneau, USA", tz: "America/Juneau" },
  // ---- A few more abroad ----
  { c: "Cabo, Mexico", tz: "America/Mazatlan" },
  { c: "Isla Mujeres, Mexico", tz: "America/Cancun" },
  { c: "Guadalajara, Mexico", tz: "America/Mexico_City" },
  { c: "San Miguel de Allende, Mexico", tz: "America/Mexico_City" },
  { c: "Providenciales, Turks and Caicos", tz: "America/Grand_Turk" },
  { c: "Grand Cayman", tz: "America/Cayman" },
  { c: "St. Thomas, USVI", tz: "America/St_Thomas" },
  { c: "St. John, USVI", tz: "America/St_Thomas" },
  { c: "Curacao", tz: "America/Curacao" },
  { c: "Bermuda", tz: "Atlantic/Bermuda" },
  { c: "Galway, Ireland", tz: "Europe/Dublin" },
  { c: "Cork, Ireland", tz: "Europe/Dublin" },
  { c: "Glasgow, Scotland", tz: "Europe/London" },
  { c: "Manchester, UK", tz: "Europe/London" },
  { c: "Bath, UK", tz: "Europe/London" },
  { c: "Cotswolds, UK", tz: "Europe/London" },
  { c: "Marseille, France", tz: "Europe/Paris" },
  { c: "Lyon, France", tz: "Europe/Paris" },
  { c: "Saint-Tropez, France", tz: "Europe/Paris" },
  { c: "Chamonix, France", tz: "Europe/Paris" },
  { c: "Verbier, Switzerland", tz: "Europe/Zurich" },
  { c: "Salzburg, Austria", tz: "Europe/Vienna" },
  { c: "Hamburg, Germany", tz: "Europe/Berlin" },
  { c: "Bologna, Italy", tz: "Europe/Rome" },
  { c: "Puglia, Italy", tz: "Europe/Rome" },
  { c: "Sardinia, Italy", tz: "Europe/Rome" },
  { c: "Granada, Spain", tz: "Europe/Madrid" },
  { c: "Tenerife, Spain", tz: "Atlantic/Canary" },
  { c: "Azores, Portugal", tz: "Atlantic/Azores" },
  { c: "Paros, Greece", tz: "Europe/Athens" },
  { c: "Naxos, Greece", tz: "Europe/Athens" },
  { c: "Rhodes, Greece", tz: "Europe/Athens" },
  { c: "Antalya, Turkey", tz: "Europe/Istanbul" },
  { c: "Marrakesh, Morocco", tz: "Africa/Casablanca" },
  { c: "Essaouira, Morocco", tz: "Africa/Casablanca" },
  { c: "Riyadh, Saudi Arabia", tz: "Asia/Riyadh" },
  { c: "Muscat, Oman", tz: "Asia/Muscat" },
  { c: "Fukuoka, Japan", tz: "Asia/Tokyo" },
  { c: "Sapporo, Japan", tz: "Asia/Tokyo" },
  { c: "Busan, South Korea", tz: "Asia/Seoul" },
  { c: "Krabi, Thailand", tz: "Asia/Bangkok" },
  { c: "Da Nang, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Lombok, Indonesia", tz: "Asia/Makassar" },
  { c: "Boracay, Philippines", tz: "Asia/Manila" },
  { c: "Cebu, Philippines", tz: "Asia/Manila" },
  { c: "Brisbane, Australia", tz: "Australia/Brisbane" },
  { c: "Byron Bay, Australia", tz: "Australia/Brisbane" },
  { c: "Adelaide, Australia", tz: "Australia/Adelaide" },
  { c: "Wanaka, New Zealand", tz: "Pacific/Auckland" },
  { c: "Wellington, New Zealand", tz: "Pacific/Auckland" },
];

/* What people actually type. Nobody searches "Outer Banks, USA" when the house
   they are looking at is in Duck, and nobody spells out Long Beach Island. */
window.CITY_ALIASES = {
  "Outer Banks, USA": ["obx", "outerbanks", "nc coast", "hatteras island"],
  "Long Beach Island, USA": ["lbi"],
  "30A, USA": ["thirty a", "30-a", "highway 30a", "scenic 30a"],
  "Martha's Vineyard, USA": ["marthas vineyard", "the vineyard", "mv"],
  "The Hamptons, USA": ["east hampton", "southampton", "sag harbor", "bridgehampton", "amagansett"],
  "Cape Cod, USA": ["the cape", "barnstable"],
  "Hilton Head, USA": ["hilton head island", "hhi"],
  "St. Simons Island, USA": ["golden isles", "saint simons"],
  "Anna Maria Island, USA": ["ami"],
  "Isle of Palms, USA": ["iop"],
  "Ocean City, Maryland, USA": ["ocmd"],
  "Ocean City, New Jersey, USA": ["ocnj"],
  "Mackinac Island, USA": ["mackinaw"],
  "Lake Tahoe, USA": ["south lake tahoe", "north lake tahoe", "tahoe"],
  "Napa Valley, USA": ["napa"],
  "Big Sur, USA": ["pacific coast highway", "pch"],
  "New York, USA": ["nyc", "manhattan", "brooklyn"],
  "Los Angeles, USA": ["la", "hollywood", "venice beach"],
  "San Francisco, USA": ["sf", "bay area"],
  "New Orleans, USA": ["nola"],
  "Washington DC, USA": ["dc", "washington"],
  "Las Vegas, USA": ["vegas"],
  "Cabo San Lucas, Mexico": ["cabo", "los cabos"],
  "Playa del Carmen, Mexico": ["riviera maya"],
  "Punta Cana, Dominican Republic": ["dr"],
  "Turks and Caicos": ["tci", "providenciales", "provo"],
};
/* Flattened once, so matching a query against aliases is a plain lookup. */
window.cityAliasHits = function (q) {
  const low = String(q || "").trim().toLowerCase();
  if (!low) return [];
  const out = [];
  const map = window.CITY_ALIASES || {};
  Object.keys(map).forEach((city) => {
    if (map[city].some((a) => a === low || a.startsWith(low) || (low.length > 2 && a.includes(low)))) out.push(city);
  });
  return out;
};

/* Look up a timezone for whatever someone typed. Exact match first, then a
   loose match on the city name, then a guess from the IANA zone list. */
window.tzForCity = function (input) {
  const raw = String(input || "").trim();
  if (!raw) return "";
  const low = raw.toLowerCase();
  const list = window.CITIES || [];
  const exact = list.find((x) => x.c.toLowerCase() === low);
  if (exact) return exact.tz;
  const head = low.split(",")[0].trim();
  const loose = list.find((x) => x.c.toLowerCase().split(",")[0].trim() === head)
             || list.find((x) => x.c.toLowerCase().includes(head) && head.length > 3);
  if (loose) return loose.tz;
  // "OBX" should still land in the right timezone
  const aliased = (window.cityAliasHits(head)[0] || "");
  if (aliased) { const hit = list.find((x) => x.c === aliased); if (hit) return hit.tz; }
  const zones = Intl.supportedValuesOf ? Intl.supportedValuesOf("timeZone") : [];
  const key = head.replace(/\s+/g, "_");
  return zones.find((z) => z.split("/").pop().toLowerCase() === key) || "";
};
