/* =============================================================================
   SquadTrip - city suggestions with real timezones.
   Typing a destination or stop fills the timezone automatically, so the
   clocks are right even when you create the trip from somewhere else.
   Anything not on this list is still accepted verbatim.
   ========================================================================== */
window.CITIES = [
  // ---- United States ----
  { c: "New York, USA", tz: "America/New_York" },
  { c: "Washington DC, USA", tz: "America/New_York" },
  { c: "Boston, USA", tz: "America/New_York" },
  { c: "Philadelphia, USA", tz: "America/New_York" },
  { c: "Miami, USA", tz: "America/New_York" },
  { c: "Orlando, USA", tz: "America/New_York" },
  { c: "Key West, USA", tz: "America/New_York" },
  { c: "Atlanta, USA", tz: "America/New_York" },
  { c: "Charleston, USA", tz: "America/New_York" },
  { c: "Savannah, USA", tz: "America/New_York" },
  { c: "Nashville, USA", tz: "America/Chicago" },
  { c: "New Orleans, USA", tz: "America/Chicago" },
  { c: "Chicago, USA", tz: "America/Chicago" },
  { c: "Austin, USA", tz: "America/Chicago" },
  { c: "Dallas, USA", tz: "America/Chicago" },
  { c: "Houston, USA", tz: "America/Chicago" },
  { c: "Minneapolis, USA", tz: "America/Chicago" },
  { c: "Denver, USA", tz: "America/Denver" },
  { c: "Aspen, USA", tz: "America/Denver" },
  { c: "Park City, USA", tz: "America/Denver" },
  { c: "Jackson Hole, USA", tz: "America/Denver" },
  { c: "Santa Fe, USA", tz: "America/Denver" },
  { c: "Phoenix, USA", tz: "America/Phoenix" },
  { c: "Scottsdale, USA", tz: "America/Phoenix" },
  { c: "Sedona, USA", tz: "America/Phoenix" },
  { c: "Las Vegas, USA", tz: "America/Los_Angeles" },
  { c: "Los Angeles, USA", tz: "America/Los_Angeles" },
  { c: "San Diego, USA", tz: "America/Los_Angeles" },
  { c: "San Francisco, USA", tz: "America/Los_Angeles" },
  { c: "Napa Valley, USA", tz: "America/Los_Angeles" },
  { c: "Palm Springs, USA", tz: "America/Los_Angeles" },
  { c: "Seattle, USA", tz: "America/Los_Angeles" },
  { c: "Portland, USA", tz: "America/Los_Angeles" },
  { c: "Honolulu, USA", tz: "Pacific/Honolulu" },
  { c: "Maui, USA", tz: "Pacific/Honolulu" },
  { c: "Kauai, USA", tz: "Pacific/Honolulu" },
  { c: "Anchorage, USA", tz: "America/Anchorage" },
  // ---- Canada ----
  { c: "Toronto, Canada", tz: "America/Toronto" },
  { c: "Montreal, Canada", tz: "America/Toronto" },
  { c: "Quebec City, Canada", tz: "America/Toronto" },
  { c: "Vancouver, Canada", tz: "America/Vancouver" },
  { c: "Whistler, Canada", tz: "America/Vancouver" },
  { c: "Banff, Canada", tz: "America/Edmonton" },
  // ---- Mexico, Caribbean, Central America ----
  { c: "Cancun, Mexico", tz: "America/Cancun" },
  { c: "Tulum, Mexico", tz: "America/Cancun" },
  { c: "Playa del Carmen, Mexico", tz: "America/Cancun" },
  { c: "Cozumel, Mexico", tz: "America/Cancun" },
  { c: "Mexico City, Mexico", tz: "America/Mexico_City" },
  { c: "Oaxaca, Mexico", tz: "America/Mexico_City" },
  { c: "Puerto Vallarta, Mexico", tz: "America/Mexico_City" },
  { c: "Sayulita, Mexico", tz: "America/Mazatlan" },
  { c: "Cabo San Lucas, Mexico", tz: "America/Mazatlan" },
  { c: "Punta Cana, Dominican Republic", tz: "America/Santo_Domingo" },
  { c: "Montego Bay, Jamaica", tz: "America/Jamaica" },
  { c: "Negril, Jamaica", tz: "America/Jamaica" },
  { c: "Nassau, Bahamas", tz: "America/Nassau" },
  { c: "Turks and Caicos", tz: "America/Grand_Turk" },
  { c: "Aruba", tz: "America/Aruba" },
  { c: "Barbados", tz: "America/Barbados" },
  { c: "St. Lucia", tz: "America/St_Lucia" },
  { c: "Antigua", tz: "America/Antigua" },
  { c: "San Juan, Puerto Rico", tz: "America/Puerto_Rico" },
  { c: "Tamarindo, Costa Rica", tz: "America/Costa_Rica" },
  { c: "La Fortuna, Costa Rica", tz: "America/Costa_Rica" },
  { c: "Belize City, Belize", tz: "America/Belize" },
  { c: "Panama City, Panama", tz: "America/Panama" },
  // ---- South America ----
  { c: "Rio de Janeiro, Brazil", tz: "America/Sao_Paulo" },
  { c: "Sao Paulo, Brazil", tz: "America/Sao_Paulo" },
  { c: "Buenos Aires, Argentina", tz: "America/Argentina/Buenos_Aires" },
  { c: "Mendoza, Argentina", tz: "America/Argentina/Mendoza" },
  { c: "Patagonia, Argentina", tz: "America/Argentina/Buenos_Aires" },
  { c: "Santiago, Chile", tz: "America/Santiago" },
  { c: "Lima, Peru", tz: "America/Lima" },
  { c: "Cusco, Peru", tz: "America/Lima" },
  { c: "Cartagena, Colombia", tz: "America/Bogota" },
  { c: "Medellin, Colombia", tz: "America/Bogota" },
  { c: "Bogota, Colombia", tz: "America/Bogota" },
  { c: "Quito, Ecuador", tz: "America/Guayaquil" },
  { c: "Montevideo, Uruguay", tz: "America/Montevideo" },
  // ---- UK & Ireland ----
  { c: "London, UK", tz: "Europe/London" },
  { c: "Edinburgh, Scotland", tz: "Europe/London" },
  { c: "Dublin, Ireland", tz: "Europe/Dublin" },
  // ---- Western & Northern Europe ----
  { c: "Paris, France", tz: "Europe/Paris" },
  { c: "Nice, France", tz: "Europe/Paris" },
  { c: "Cannes, France", tz: "Europe/Paris" },
  { c: "Bordeaux, France", tz: "Europe/Paris" },
  { c: "Provence, France", tz: "Europe/Paris" },
  { c: "Amsterdam, Netherlands", tz: "Europe/Amsterdam" },
  { c: "Brussels, Belgium", tz: "Europe/Brussels" },
  { c: "Berlin, Germany", tz: "Europe/Berlin" },
  { c: "Munich, Germany", tz: "Europe/Berlin" },
  { c: "Vienna, Austria", tz: "Europe/Vienna" },
  { c: "Zurich, Switzerland", tz: "Europe/Zurich" },
  { c: "Interlaken, Switzerland", tz: "Europe/Zurich" },
  { c: "Zermatt, Switzerland", tz: "Europe/Zurich" },
  { c: "Copenhagen, Denmark", tz: "Europe/Copenhagen" },
  { c: "Stockholm, Sweden", tz: "Europe/Stockholm" },
  { c: "Oslo, Norway", tz: "Europe/Oslo" },
  { c: "Helsinki, Finland", tz: "Europe/Helsinki" },
  { c: "Reykjavik, Iceland", tz: "Atlantic/Reykjavik" },
  // ---- Southern Europe ----
  { c: "Barcelona, Spain", tz: "Europe/Madrid" },
  { c: "Madrid, Spain", tz: "Europe/Madrid" },
  { c: "Seville, Spain", tz: "Europe/Madrid" },
  { c: "Valencia, Spain", tz: "Europe/Madrid" },
  { c: "San Sebastian, Spain", tz: "Europe/Madrid" },
  { c: "Ibiza, Spain", tz: "Europe/Madrid" },
  { c: "Mallorca, Spain", tz: "Europe/Madrid" },
  { c: "Lisbon, Portugal", tz: "Europe/Lisbon" },
  { c: "Porto, Portugal", tz: "Europe/Lisbon" },
  { c: "Algarve, Portugal", tz: "Europe/Lisbon" },
  { c: "Madeira, Portugal", tz: "Atlantic/Madeira" },
  { c: "Rome, Italy", tz: "Europe/Rome" },
  { c: "Florence, Italy", tz: "Europe/Rome" },
  { c: "Venice, Italy", tz: "Europe/Rome" },
  { c: "Milan, Italy", tz: "Europe/Rome" },
  { c: "Naples, Italy", tz: "Europe/Rome" },
  { c: "Amalfi Coast, Italy", tz: "Europe/Rome" },
  { c: "Positano, Italy", tz: "Europe/Rome" },
  { c: "Capri, Italy", tz: "Europe/Rome" },
  { c: "Sicily, Italy", tz: "Europe/Rome" },
  { c: "Tuscany, Italy", tz: "Europe/Rome" },
  { c: "Lake Como, Italy", tz: "Europe/Rome" },
  { c: "Athens, Greece", tz: "Europe/Athens" },
  { c: "Santorini, Greece", tz: "Europe/Athens" },
  { c: "Mykonos, Greece", tz: "Europe/Athens" },
  { c: "Crete, Greece", tz: "Europe/Athens" },
  { c: "Corfu, Greece", tz: "Europe/Athens" },
  { c: "Dubrovnik, Croatia", tz: "Europe/Zagreb" },
  { c: "Split, Croatia", tz: "Europe/Zagreb" },
  { c: "Hvar, Croatia", tz: "Europe/Zagreb" },
  { c: "Budapest, Hungary", tz: "Europe/Budapest" },
  { c: "Prague, Czech Republic", tz: "Europe/Prague" },
  { c: "Krakow, Poland", tz: "Europe/Warsaw" },
  { c: "Ljubljana, Slovenia", tz: "Europe/Ljubljana" },
  { c: "Malta", tz: "Europe/Malta" },
  { c: "Istanbul, Turkey", tz: "Europe/Istanbul" },
  { c: "Cappadocia, Turkey", tz: "Europe/Istanbul" },
  { c: "Bodrum, Turkey", tz: "Europe/Istanbul" },
  // ---- Africa & Middle East ----
  { c: "Marrakech, Morocco", tz: "Africa/Casablanca" },
  { c: "Fes, Morocco", tz: "Africa/Casablanca" },
  { c: "Casablanca, Morocco", tz: "Africa/Casablanca" },
  { c: "Cairo, Egypt", tz: "Africa/Cairo" },
  { c: "Cape Town, South Africa", tz: "Africa/Johannesburg" },
  { c: "Johannesburg, South Africa", tz: "Africa/Johannesburg" },
  { c: "Kruger, South Africa", tz: "Africa/Johannesburg" },
  { c: "Nairobi, Kenya", tz: "Africa/Nairobi" },
  { c: "Zanzibar, Tanzania", tz: "Africa/Dar_es_Salaam" },
  { c: "Serengeti, Tanzania", tz: "Africa/Dar_es_Salaam" },
  { c: "Accra, Ghana", tz: "Africa/Accra" },
  { c: "Lagos, Nigeria", tz: "Africa/Lagos" },
  { c: "Dakar, Senegal", tz: "Africa/Dakar" },
  { c: "Seychelles", tz: "Indian/Mahe" },
  { c: "Mauritius", tz: "Indian/Mauritius" },
  { c: "Dubai, UAE", tz: "Asia/Dubai" },
  { c: "Abu Dhabi, UAE", tz: "Asia/Dubai" },
  { c: "Doha, Qatar", tz: "Asia/Qatar" },
  { c: "Tel Aviv, Israel", tz: "Asia/Jerusalem" },
  { c: "Amman, Jordan", tz: "Asia/Amman" },
  // ---- Asia ----
  { c: "Tokyo, Japan", tz: "Asia/Tokyo" },
  { c: "Kyoto, Japan", tz: "Asia/Tokyo" },
  { c: "Osaka, Japan", tz: "Asia/Tokyo" },
  { c: "Hakone, Japan", tz: "Asia/Tokyo" },
  { c: "Seoul, South Korea", tz: "Asia/Seoul" },
  { c: "Bangkok, Thailand", tz: "Asia/Bangkok" },
  { c: "Phuket, Thailand", tz: "Asia/Bangkok" },
  { c: "Chiang Mai, Thailand", tz: "Asia/Bangkok" },
  { c: "Koh Samui, Thailand", tz: "Asia/Bangkok" },
  { c: "Bali, Indonesia", tz: "Asia/Makassar" },
  { c: "Jakarta, Indonesia", tz: "Asia/Jakarta" },
  { c: "Singapore", tz: "Asia/Singapore" },
  { c: "Kuala Lumpur, Malaysia", tz: "Asia/Kuala_Lumpur" },
  { c: "Ho Chi Minh City, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Hanoi, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Hoi An, Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { c: "Siem Reap, Cambodia", tz: "Asia/Phnom_Penh" },
  { c: "Manila, Philippines", tz: "Asia/Manila" },
  { c: "Palawan, Philippines", tz: "Asia/Manila" },
  { c: "Hong Kong", tz: "Asia/Hong_Kong" },
  { c: "Taipei, Taiwan", tz: "Asia/Taipei" },
  { c: "Shanghai, China", tz: "Asia/Shanghai" },
  { c: "Beijing, China", tz: "Asia/Shanghai" },
  { c: "Delhi, India", tz: "Asia/Kolkata" },
  { c: "Mumbai, India", tz: "Asia/Kolkata" },
  { c: "Jaipur, India", tz: "Asia/Kolkata" },
  { c: "Udaipur, India", tz: "Asia/Kolkata" },
  { c: "Goa, India", tz: "Asia/Kolkata" },
  { c: "Kerala, India", tz: "Asia/Kolkata" },
  { c: "Colombo, Sri Lanka", tz: "Asia/Colombo" },
  { c: "Kathmandu, Nepal", tz: "Asia/Kathmandu" },
  { c: "Maldives", tz: "Indian/Maldives" },
  // ---- Oceania ----
  { c: "Sydney, Australia", tz: "Australia/Sydney" },
  { c: "Melbourne, Australia", tz: "Australia/Melbourne" },
  { c: "Gold Coast, Australia", tz: "Australia/Brisbane" },
  { c: "Cairns, Australia", tz: "Australia/Brisbane" },
  { c: "Perth, Australia", tz: "Australia/Perth" },
  { c: "Auckland, New Zealand", tz: "Pacific/Auckland" },
  { c: "Queenstown, New Zealand", tz: "Pacific/Auckland" },
  { c: "Fiji", tz: "Pacific/Fiji" },
  { c: "Bora Bora", tz: "Pacific/Tahiti" },
  { c: "Tahiti", tz: "Pacific/Tahiti" },
  { c: "Cook Islands", tz: "Pacific/Rarotonga" },
];

/* Look up a timezone for whatever someone typed. Exact match first, then a
   loose match on the city name, then a guess from the IANA zone list. */
window.tzForCity = function (input) {
  const raw = String(input || "").trim();
  if (!raw) return "";
  const low = raw.toLowerCase();
  const list = window.CITIES || [];
  const exact = list.find((x) => x.c.toLowerCase() === low);
  if (exact) return exact.tz;
  const head = low.split(",")[0].trim();
  const loose = list.find((x) => x.c.toLowerCase().split(",")[0].trim() === head)
             || list.find((x) => x.c.toLowerCase().includes(head) && head.length > 3);
  if (loose) return loose.tz;
  const zones = Intl.supportedValuesOf ? Intl.supportedValuesOf("timeZone") : [];
  const key = head.replace(/\s+/g, "_");
  return zones.find((z) => z.split("/").pop().toLowerCase() === key) || "";
};
